In [4]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [5]:
df = pd.read_csv('grapes_new.csv')
df

,COLOR_INTENSITY,SHAPE,RIPENESS_PER,ALCOHOL_PER,MALIC_ACID_PER,ASH,ALCALINITY_OF_ASH,MAGNESIUM_MEASURE,TOTAL_PHENOLS,FLAVANOIDS,...,HUE,PROLINE,TEMPERATURE,AVG_HUMIDITY,FERT_NITRO_PER,WATER_O2_PER,WATER_PH,FER_P2O5_PER,SOIL_TYPE,CLASS
0,120.53,elliptical,16.73,14.23,1.71,2.43,15.6,127,2.80,3.06,...,1.04,1065,23.34,54.99,31.21,97.67,7.71,52.02,archean,High
1,112.57,elliptical,20.30,13.20,1.78,2.14,11.2,100,2.65,2.76,...,1.05,1050,23.40,51.91,31.28,99.05,7.66,48.18,archean,High
2,120.78,elliptical,20.81,13.16,2.36,2.67,18.6,101,2.80,3.24,...,1.03,1185,22.29,50.69,31.92,97.95,7.66,28.15,archean,High
3,134.17,elliptical,19.47,14.37,1.95,2.50,16.8,113,3.85,3.49,...,0.86,1480,21.28,47.72,31.79,95.46,7.21,55.95,alluvial,High
4,112.19,round,17.57,13.24,2.59,2.87,21.0,118,2.80,2.69,...,1.04,735,23.76,45.09,31.86,94.45,7.80,55.99,archean,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189,102.34,elliptical,21.23,12.07,2.16,2.17,21.0,85,2.60,2.65,...,0.86,378,25.58,46.15,30.14,89.52,8.49,55.83,alluvial,Medium
190,109.80,elliptical,21.67,12.43,1.53,2.29,NaN,86,2.74,3.15,...,0.69,352,24.23,52.23,30.72,85.91,7.73,55.47,archean,Medium
191,103.86,round,22.01,11.79,2.13,2.78,28.5,92,2.13,2.24,...,0.97,466,27.62,48.98,30.46,86.31,7.57,47.57,archean,Medium
192,98.30,elliptical,21.95,12.37,1.63,2.30,24.5,88,2.22,2.45,...,0.89,342,27.54,47.72,30.01,90.60,7.15,45.91,alluvial,Medium
193,101.33,elliptical,21.60,12.04,4.30,2.38,NaN,80,2.10,1.75,...,0.79,580,25.10,55.42,30.89,88.14,6.68,52.42,archean,Medium

In [6]:
onehot_encoder_shape = OneHotEncoder(sparse_output=False)
shape_encoded = onehot_encoder_shape.fit_transform(df[['SHAPE']])
shape_encoded_df = pd.DataFrame(shape_encoded, columns=onehot_encoder_shape.get_feature_names_out(['SHAPE']))

# Initialize OneHotEncoder for 'SOIL_TYPE'
onehot_encoder_soil = OneHotEncoder(sparse_output=False)
soil_type_encoded = onehot_encoder_soil.fit_transform(df[['SOIL_TYPE']])
soil_type_encoded_df = pd.DataFrame(soil_type_encoded, columns=onehot_encoder_soil.get_feature_names_out(['SOIL_TYPE']))

# Concatenate the original dataframe with the one-hot encoded columns
df_encoded = pd.concat([df, shape_encoded_df, soil_type_encoded_df], axis=1)
df_encoded.head()

,COLOR_INTENSITY,SHAPE,RIPENESS_PER,ALCOHOL_PER,MALIC_ACID_PER,ASH,ALCALINITY_OF_ASH,MAGNESIUM_MEASURE,TOTAL_PHENOLS,FLAVANOIDS,...,FERT_NITRO_PER,WATER_O2_PER,WATER_PH,FER_P2O5_PER,SOIL_TYPE,CLASS,SHAPE_elliptical,SHAPE_round,SOIL_TYPE_alluvial,SOIL_TYPE_archean
0,120.53,elliptical,16.73,14.23,1.71,2.43,15.6,127,2.80,3.06,...,31.21,97.67,7.71,52.02,archean,High,1.0,0.0,0.0,1.0
1,112.57,elliptical,20.30,13.20,1.78,2.14,11.2,100,2.65,2.76,...,31.28,99.05,7.66,48.18,archean,High,1.0,0.0,0.0,1.0
2,120.78,elliptical,20.81,13.16,2.36,2.67,18.6,101,2.80,3.24,...,31.92,97.95,7.66,28.15,archean,High,1.0,0.0,0.0,1.0
3,134.17,elliptical,19.47,14.37,1.95,2.50,16.8,113,3.85,3.49,...,31.79,95.46,7.21,55.95,alluvial,High,1.0,0.0,1.0,0.0
4,112.19,round,17.57,13.24,2.59,2.87,21.0,118,2.80,2.69,...,31.86,94.45,7.80,55.99,archean,High,0.0,1.0,0.0,1.0

In [7]:
df_encoded.drop(['SHAPE', 'SOIL_TYPE'], axis=1, inplace=True)
df_encoded.head()

,COLOR_INTENSITY,RIPENESS_PER,ALCOHOL_PER,MALIC_ACID_PER,ASH,ALCALINITY_OF_ASH,MAGNESIUM_MEASURE,TOTAL_PHENOLS,FLAVANOIDS,PROANTHOCYANINS,...,AVG_HUMIDITY,FERT_NITRO_PER,WATER_O2_PER,WATER_PH,FER_P2O5_PER,CLASS,SHAPE_elliptical,SHAPE_round,SOIL_TYPE_alluvial,SOIL_TYPE_archean
0,120.53,16.73,14.23,1.71,2.43,15.6,127,2.80,3.06,2.29,...,54.99,31.21,97.67,7.71,52.02,High,1.0,0.0,0.0,1.0
1,112.57,20.30,13.20,1.78,2.14,11.2,100,2.65,2.76,1.28,...,51.91,31.28,99.05,7.66,48.18,High,1.0,0.0,0.0,1.0
2,120.78,20.81,13.16,2.36,2.67,18.6,101,2.80,3.24,2.81,...,50.69,31.92,97.95,7.66,28.15,High,1.0,0.0,0.0,1.0
3,134.17,19.47,14.37,1.95,2.50,16.8,113,3.85,3.49,2.18,...,47.72,31.79,95.46,7.21,55.95,High,1.0,0.0,1.0,0.0
4,112.19,17.57,13.24,2.59,2.87,21.0,118,2.80,2.69,1.82,...,45.09,31.86,94.45,7.80,55.99,High,0.0,1.0,0.0,1.0

In [8]:
numerical_columns = df.select_dtypes(include=['float64', 'int64']).columns

In [9]:
standard_scaler = StandardScaler()
standard_scaled_data = standard_scaler.fit_transform(df_encoded[numerical_columns])
standard_scaled_df = pd.DataFrame(standard_scaled_data, columns=numerical_columns)
standard_scaled_df.head()

,COLOR_INTENSITY,RIPENESS_PER,ALCOHOL_PER,MALIC_ACID_PER,ASH,ALCALINITY_OF_ASH,MAGNESIUM_MEASURE,TOTAL_PHENOLS,FLAVANOIDS,PROANTHOCYANINS,HUE,PROLINE,TEMPERATURE,AVG_HUMIDITY,FERT_NITRO_PER,WATER_O2_PER,WATER_PH,FER_P2O5_PER
0,0.255165,-2.009212,1.493202,-0.560552,0.241672,-1.134065,1.921754,0.795585,1.044432,1.263833,0.370177,0.985908,-1.014412,1.194907,0.576341,1.400377,0.057058,0.947304
1,-0.301626,-0.509425,0.217659,-0.497781,-0.842576,-2.418428,0.022481,0.558498,0.744062,-0.526993,0.414110,0.938331,-0.994640,0.278019,0.638621,1.658322,-0.041248,0.577054
2,0.272652,-0.295170,0.168123,0.022326,1.138981,-0.258363,0.092824,0.795585,1.224655,2.185842,0.326245,1.366524,-1.360432,-0.085164,1.208036,1.452714,-0.041248,-1.354224
3,1.209263,-0.858115,1.666577,-0.345336,0.503387,-0.783784,0.936946,2.455191,1.474963,1.068792,-0.420608,2.302206,-1.693269,-0.969306,1.092374,0.987292,-0.925996,1.326232
4,-0.328207,-1.656321,0.267194,0.228575,1.886739,0.442198,1.288663,0.795585,0.673976,0.430478,0.370177,-0.060787,-0.876005,-1.752234,1.154654,0.798507,0.234007,1.330089

In [10]:
min_max_scaler = MinMaxScaler()
min_max_scaled_data = min_max_scaler.fit_transform(df_encoded[numerical_columns])
min_max_scaled_df = pd.DataFrame(min_max_scaled_data, columns=numerical_columns)
min_max_scaled_df.head()

,COLOR_INTENSITY,RIPENESS_PER,ALCOHOL_PER,MALIC_ACID_PER,ASH,ALCALINITY_OF_ASH,MAGNESIUM_MEASURE,TOTAL_PHENOLS,FLAVANOIDS,PROANTHOCYANINS,HUE,PROLINE,TEMPERATURE,AVG_HUMIDITY,FERT_NITRO_PER,WATER_O2_PER,WATER_PH,FER_P2O5_PER
0,0.372027,0.062016,0.842105,0.191700,0.572193,0.257732,0.619565,0.627586,0.573840,0.593060,0.455285,0.561341,0.204947,0.784257,0.545455,0.891808,0.603015,0.783460
1,0.264459,0.457364,0.571053,0.205534,0.417112,0.030928,0.326087,0.575862,0.510549,0.274448,0.463415,0.550642,0.210247,0.559767,0.556240,0.962906,0.577889,0.689503
2,0.375405,0.513843,0.560526,0.320158,0.700535,0.412371,0.336957,0.627586,0.611814,0.757098,0.447154,0.646933,0.112191,0.470845,0.654854,0.906234,0.577889,0.199413
3,0.556351,0.365449,0.878947,0.239130,0.609626,0.319588,0.467391,0.989655,0.664557,0.558360,0.308943,0.857347,0.022968,0.254373,0.634823,0.777950,0.351759,0.879618
4,0.259324,0.155039,0.581579,0.365613,0.807487,0.536082,0.521739,0.627586,0.495781,0.444795,0.455285,0.325963,0.242049,0.062682,0.645609,0.725914,0.648241,0.880597

In [11]:
df['CLASS'].value_counts()

CLASS
Medium    76
High      64
Low       54
Name: count, dtype: int64